basics:
	sbt "runMain Basics"

laziness:
	sbt "runMain Laziness"

grouping:
	sbt "runMain Grouping"

fusion:
	sbt "runMain Fusion"

page_rank:
	sbt "runMain PageRank"

map_reduce:
	sbt "runMain MapReduce"

