// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.8
// source: greeter.proto

package greeter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sayer_SayHello_FullMethodName = "/greeter.Sayer/SayHello"
)

// SayerClient is the client API for Sayer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SayerClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type sayerClient struct {
	cc grpc.ClientConnInterface
}

func NewSayerClient(cc grpc.ClientConnInterface) SayerClient {
	return &sayerClient{cc}
}

func (c *sayerClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Sayer_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayerServer is the server API for Sayer service.
// All implementations must embed UnimplementedSayerServer
// for forward compatibility.
type SayerServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedSayerServer()
}

// UnimplementedSayerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSayerServer struct{}

func (UnimplementedSayerServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSayerServer) mustEmbedUnimplementedSayerServer() {}
func (UnimplementedSayerServer) testEmbeddedByValue()               {}

// UnsafeSayerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SayerServer will
// result in compilation errors.
type UnsafeSayerServer interface {
	mustEmbedUnimplementedSayerServer()
}

func RegisterSayerServer(s grpc.ServiceRegistrar, srv SayerServer) {
	// If the following call panics, it indicates UnimplementedSayerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sayer_ServiceDesc, srv)
}

func _Sayer_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sayer_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayerServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sayer_ServiceDesc is the grpc.ServiceDesc for Sayer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sayer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greeter.Sayer",
	HandlerType: (*SayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Sayer_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}

const (
	Asker_AskHello_FullMethodName = "/greeter.Asker/AskHello"
)

// AskerClient is the client API for Asker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AskerClient interface {
	AskHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type askerClient struct {
	cc grpc.ClientConnInterface
}

func NewAskerClient(cc grpc.ClientConnInterface) AskerClient {
	return &askerClient{cc}
}

func (c *askerClient) AskHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Asker_AskHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AskerServer is the server API for Asker service.
// All implementations must embed UnimplementedAskerServer
// for forward compatibility.
type AskerServer interface {
	AskHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedAskerServer()
}

// UnimplementedAskerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAskerServer struct{}

func (UnimplementedAskerServer) AskHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AskHello not implemented")
}
func (UnimplementedAskerServer) mustEmbedUnimplementedAskerServer() {}
func (UnimplementedAskerServer) testEmbeddedByValue()               {}

// UnsafeAskerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AskerServer will
// result in compilation errors.
type UnsafeAskerServer interface {
	mustEmbedUnimplementedAskerServer()
}

func RegisterAskerServer(s grpc.ServiceRegistrar, srv AskerServer) {
	// If the following call panics, it indicates UnimplementedAskerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Asker_ServiceDesc, srv)
}

func _Asker_AskHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskerServer).AskHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Asker_AskHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskerServer).AskHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Asker_ServiceDesc is the grpc.ServiceDesc for Asker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Asker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greeter.Asker",
	HandlerType: (*AskerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskHello",
			Handler:    _Asker_AskHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}
