apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  containers:
    - name: container-a
      image: busybox
      command: ["sleep", "3600"]
    - name: container-b
      image: busybox
      command: ["sleep", "3600"]
