start:
	minikube start

check:
	kubectl get nodes

apply:
	kubectl apply -f basics.yaml

list_pods:
	kubectl get pods

delete_pod:
	kubectl delete pod $(POD)

cleanup:
	kubectl delete -f basics.yaml

